version: "3.8"

services:
  web:
    build:
      context: .
      target: deps
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    # Enable for Apple Silicon / M1/M2 chips
    # platform: linux/amd64

  # Production build
  web-prod:
    build:
      context: .
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # Enable for Apple Silicon / M1/M2 chips
    # platform: linux/amd64
